# Generated by Django 5.2.6 on 2025-09-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_compra',
        ),
        migrations.AddField(
            model_name='lote',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio de Compra del Lote'),
        ),
    ]
