# Generated by Django 5.2.6 on 2025-09-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_cierre', models.DateTimeField(auto_now_add=True)),
                ('total_calculado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_efectivo_real', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diferencia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_tickets', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Cierre de Caja',
                'verbose_name_plural': 'Cierres de Caja',
                'ordering': ['-fecha_hora_cierre'],
            },
        ),
    ]
