# Generated by Django 5.1.2 on 2025-10-17 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Cierre')),
                ('total_sistema', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Calculado por Sistema')),
                ('total_arqueo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Contado (Arqueo)')),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Diferencia')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que cierra')),
            ],
            options={
                'verbose_name': 'Cierre de Caja',
                'verbose_name_plural': 'Cierres de Caja',
                'ordering': ['-fecha_cierre'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCierre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_sistema', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Sistema')),
                ('monto_arqueo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Contado')),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='cierres.cierrecaja')),
            ],
            options={
                'verbose_name': 'Detalle de Cierre',
                'verbose_name_plural': 'Detalles de Cierre',
            },
        ),
    ]
