# Generated by Django 5.1.2 on 2025-10-17 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cierres', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecierre',
            name='metodo_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.metodopago', verbose_name='Método de Pago'),
        ),
        migrations.AlterUniqueTogether(
            name='detallecierre',
            unique_together={('cierre', 'metodo_pago')},
        ),
    ]
