# Generated by Django 5.1.2 on 2025-10-12 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Método de Pago')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='precio_unitario',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='precio_compra_momento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio de Compra en el Momento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='precio_unitario_momento',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Precio Unitario en el Momento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.metodopago', verbose_name='Método de Pago'),
        ),
    ]
